### ISSUE TITLE
Join the Programming Formalisms Summer 2024

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_project_autumn_2024#1]
Share your GitHub username here and we'll add you to the team :-)

This is needed to work on the learners' project at https://github.com/programming-formalisms/programming_formalisms_project_autumn_2024 👍

After having joined the project, you will get a lot of emails. Select the following 'Watch' setting to only get emails related to you:

![how_to_unwatch](https://github.com/user-attachments/assets/69b8d421-593c-415e-a13f-b0ea9a4ba9cb)

**Comment by piiamt** [comment]
piiamt

**Comment by bclaremar** [comment]
bclaremar

**Comment by Gabi86** [comment]
Gabi86

**Comment by formersbach** [comment]
formersbach

**Comment by emiliamoralest** [comment]
emiliamoralest

**Comment by llvillanueva** [comment]
llvillanueva

**Comment by JonssonGustav97** [comment]
JonssonGustav97

**Comment by brunakatiele** [comment]
brunakatiele

**Comment by annelinilsson** [comment]
annelinilsson

**Comment by richelbilderbeek** [comment]
All 9 learners have gotten an invite now :+1:

**Comment by richelbilderbeek** [comment]
Only Athaianos needs to be added: he came in briefly and left in short time, because of his (missing) Zoom setup :-)

**Comment by richelbilderbeek** [comment]
I assume all learners are in the project by now. Done!
