### ISSUE TITLE
Creating is_prime

### ISSUE THREAD

**Issue by JonssonGustav97** [programming-formalisms/programming_formalisms_project_autumn_2024#27]
Creating a function that determines if inpout is a prime number

**Comment by richelbilderbeek** [comment]
I've updated the rule for creating issues at https://uppmax.github.io/programming_formalisms/project/issues/#our-project to only create issues for project-related things. I feel this is a better rule, as it feels too much bureaucracy to create an issue for a regular exercise.

I hence will close all issues that are related to regular exercises.
