### ISSUE TITLE
Fix the tests on the main branch

### ISSUE THREAD

**Issue by richelbilderbeek** [programming-formalisms/programming_formalisms_project_autumn_2024#56]
Currently, the tests on the main branch is broken, as seen in [this 'Measure codecov' error log](https://github.com/programming-formalisms/programming_formalisms_project_autumn_2024/actions/runs/11932031065/job/33256146254)

As `main` should always work -and in this case, it does not- fix these directly on the `main` branch.

**Comment by pamella-miranda** [comment]
- [ ] task

**Comment by pamella-miranda** [comment]
- [ ]  test_is_zero (tests.test_anneli.TestAnneli) --> TypeError: 'x' must be of type int
- [ ]  tests.test_gustav (unittest.loader._FailedTest) --> SyntaxError: expected ':'
- [ ]  test_isprime (tests.test_richel_utils.TestRichelUtils) --> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'
